# Generated by Django 4.2.5 on 2024-12-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workboards', '0002_alter_workboards_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workboards',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
