# Generated by Django 4.2.5 on 2024-12-17 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasklists', '0002_alter_tasklists_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('status', models.CharField(choices=[('1', 'Done'), ('2', 'Progressing'), ('3', 'On Hold'), ('4', 'Failed')], default='2', max_length=1)),
                ('comment', models.TextField(blank=True, default='', null=True)),
                ('participants', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tasklists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasklists.tasklists')),
            ],
        ),
    ]
