# Generated by Django 4.2.5 on 2024-12-17 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_tasks_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='comment',
        ),
    ]
