# Generated by Django 4.2.5 on 2024-12-17 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tasks_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='tasklists',
            new_name='tasklist',
        ),
    ]
