# Generated by Django 4.2.5 on 2024-12-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
